---
- hosts: all
  become: true
  tasks:
    
    - name: Installing apache2 service
      apt:
         name: apache2
         state: present
         
    - name: Starting the service
      service:
          name: apache2
          status: started
          enabled: yes
    - name: Copying index file
      copy: 
         src: index.html
         dest: /var/www/html/index.html
