---
- hosts: webserver
  become: true
  tasks:
    
    - name: Installing apache2 service
      apt:
         name: apache2
         state: present
         update_cache: yes
         
    - name: Starting the service
      service:
          name: apache2
          state: started
          enabled: yes
          
    #- name: Copying index file
     # copy: 
      #   src: index.html
       #  dest: /var/www/html/index.html
       
    - name: Downloading the website template
      get_url: 
          url: https://www.tooplate.com/zip-templates/2124_vertex.zip
          dest: /home/ubuntu/
         # reomte_src: yes
      #become: true
             
    - name: unarchive
      unarchive: 
        src: /home/ubuntu/2124_vertex.zip
        dest: /tmp/
        remote_src: yes
          
   # - name: copying files in apache2 location
    #  shell: cp -rf /tmp/2124_vertex/* /var/www/html/ 
      
