---
- hosts: webserver
  become: true
  tasks:
    
    - name: Installing apache2 service
      apt:
         name: apache2
         state: present
         update_cache: yes
         
         
    - name: Starting the service
      service:
          name: apache2
          state: started
          enabled: yes
          
    #- name: Copying index file
     # copy: 
      #   src: index.html
       #  dest: /var/www/html/index.html
       
    - name: unarchive
      unarchive: 
          src: /home/ubuntu/2121_wave_cafe.zip
          dest: /tmp/
          remote_src: yes
