---
- hosts: webserver
  become: true
  tasks:
    
    - name: Installing apache2 service
      apt:
         name: httpd
         state: present
         #update_cache: yes
         
    - name: Starting the service
      service:
          name: httpd
          state: started
          enabled: yes
          
    - name: Copying index file
      copy: 
         src: index.html
         dest: /var/www/html/index.html
