
---
- hosts: webserver
  become: true
  tasks:
      
      - name: Installing Jdk 
        apt:
          name: openjdk-8-jdk
          state: present
          
      - name: get_installer
        get_url:
           url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.76/bin/apache-tomcat-7.0.76.tar.gz
           dest: /tmp/
      
   
      
     
